constants:
########### DICE version specific parameters ##################################
    Tstep: 1  # Years in one time step
    Version: '2016'  #  Version of DICE 2007 or 2016 or cjl

########### Numeric parameters ################################################
    vartheta: 0.02  # Purely numeric parameter to transform time periods

########### Exogenous processes ###############################################
  # Population
    L0: 5242.35  #3359.9868  # World population in 2005 [millions]
    Linfty: 11500  # Asymptotic world population [millions]
    deltaL: 0.012  # Rate of convergence to asymptotic world population
  # Total factor productivity in effective labor units
    A0hat: 0.00604437 #0.00304515 #0.02183642 #0.5485 #0.02183  # Initial level of TFP
    gA0hat: 0.01  # Initial growth rate of TFP
  # energy
#     e0: 1.334
#     gen: 0.01
    edt0: 0.2251
    ecl0: 0.04758
    gedt: 0.02
    gecl: 0.02
    

########### Economic parameters ###############################################
  # Utility function
    rho0: 0.015 # Pure rate of time preference
    rhoCES: 1.5 #CES elasticity
  # Epstein-Zin preferences
    psi0: 1.5  # Inter-temporal elasticity of substitution
  # Production function
    alpha: 0.3  # Capital elasticity
    delta: 0.1  # Annual capital depreciation rate
    nu: 0.04

########## Initial states #####################################################
    k0: 5.2748  # K0/(A1L0)
    tau0: 0.  # Initial time period (corresponding to 2015)

