constants:
########### DICE version specific parameters ##################################
    Tstep: 1  # Years in one time step
    Version: '2016'  #  Version of DICE 2007 or 2016 or cjl

########### Numeric parameters ################################################
    vartheta: 0.02  # Purely numeric parameter to transform time periods

########### Exogenous processes ###############################################
  # Population
    L0: 7403  # World population in 2005 [millions]
    Linfty: 11500  # Asymptotic world population [millions]
    deltaL: 0.0268  # Rate of convergence to asymptotic world population
  # Total factor productivity in effective labor units
    A0hat: 0.010295  # Initial level of TFP
    gA0hat: 0.0217  # Initial growth rate of TFP
    deltaA: 0.005  # Rate of decline in growth of the productivity
  # Carbon intensity
    sigma0: 0.0000955592  # Initial carbon instensity
    deltaSigma: 0.001  # Decline rate of decarbonization per year
    gSigma0: -0.0152  # Initial growth of carbon intensity per year
  # Mitigation
    theta2: 2.6  # Mitigation cost parameter
    pback: 0.55  # Cost of backstop 2010 thousand USD per tCo2 2015
    gback: 0.005  # Initial cost decline backstop cost per year
    c2co2: 3.666  # Transformation from c to co2
  # Land emissions
    ELand0: 0.00070922  # Emissions form land in 2005 (1000GtC per year)
    deltaLand: 0.023  # Decline rate of land amissions (per year)
  # Land emissions
    fex0: 0.5  # Forcing of nonCO2 GHG (Wm-2) in 2000
    fex1: 1.0  # Forcing of nonCO2 GHG (Wm-2) in 2100
    Tyears: 85.  # Number of years before 2100

########### Bayesian learning related parameters ###############################
    Delta_t2xco20: 1.2 #1.2
    SepsT: 0.01

########### Economic parameters ###############################################
  # Utility function
    rho0: 0.015  # Pure rate of time preference
  # Epstein-Zin preferences
    psi0: 1.5  # Inter-temporal elasticity of substitution
    gamma0: 10.  # Risk-aversion parameter
  # Production function
    alpha: 0.3  # Capital elasticity
    delta: 0.1  # Annual capital depreciation rate
  # Damage function
    pi1: 0  # Climate damage factor coefficient
    pi20: 0.00236  # Climate damage factor coefficient

########### cdice carbon mass #############################################
    phi12_: 0.054  # Rate of carbon diffusion from atmosphere to upper ocean
    phi23_: 0.0082  # Rate of carbon diffusion from upper ocean to lower ocean
    MATeq: 0.607  # Equilibrium mass of carbon in the Atmosphere
    MUOeq: 0.489  # Equilibrium mass of carbon in the upper ocean
    MLOeq: 1.281  # Equilibrium mass of carbon in the lower ocean

########### cdice temperature #############################################
    varphi1_: 0.137  # Temperature coefficient
    varphi3_: 0.73  # Temperature coefficient
    varphi4_: 0.00689  # Temperature coefficient
    f2xco20: 3.45  # Radiative forcing parameter
    t2xco20: 3.25  # Equilibrium climate temperature
    MATbase: 0.607  # Preindustrial atmospheric carbon concentration

########## Initial states #####################################################
    k0: 2.926  # K0/(A0L0)
    MAT0: 0.851  # [1000 GtC] Doris calibration
    MUO0: 0.628  # [1000 GtC] Doris calibration
    MLO0: 1.323  # [1000 GtC] Doris calibration
    TAT0: 1.1  # [oC relative to the preindustrial] Doris calibration
    TOC0: 0.27  # [oC relative to the preindustrial] Doris calibration
    muf0: 0.65
    Sf0: 0.0169
    tau0: 0.  # Initial time period (corresponding to 2015)

########## Lower and upper bounds of the uncertain parameters #################
    UQflag: True
  # Climate feedback parameters
    muf_lower: 0.45
    muf_upper: 0.73
    Sf_lower: 0.0169
    Sf_upper: 0.0169

  # Pure rate of time preference
    rho_lower: 0.01
    rho_upper: 0.02
  # Risk-aversion
    gamma_lower: 2.5
    gamma_upper: 12.5
  # Intertemporal elasticity of substitution
    psi_lower: 1.2
    psi_upper: 2.

  # Damage function parameter
    pi2_lower: 0.002
    pi2_upper: 0.008

########## Polynomial chaos expansions ########################################
    poly_order: 4

########## Gaussian process surrogate model ###################################
    N_train_X: 50
