# --------------------------------------------------------------------------- #
# State variables
# --------------------------------------------------------------------------- #
states:
  # ------------------------------------------------------------------------- #
  # Economic state
  # ------------------------------------------------------------------------- #
  - name: kx  # Capital stock in period t in effective labor units
    init:
      distribution: truncated_normal
      kwargs:
        mean: 4.5
        stddev: 0.0


  # ------------------------------------------------------------------------- #
  # Time state variable
  # ------------------------------------------------------------------------- #
  - name: taux  # Computational time
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.  # Starting year is 2015
        stddev: 0.


# --------------------------------------------------------------------------- #
# Policy variables
# --------------------------------------------------------------------------- #
policies:
  - name: invy  # Investment policy
    activation: tf.keras.activations.softplus

  - name: cony  # Consumption policy
    activation: tf.keras.activations.softplus
    
  - name: kmny  # production capital
    activation: tf.keras.activations.softplus
    
  - name: kdty  # dirty capital
    activation: tf.keras.activations.softplus

  - name: kcly  # clean capital
    activation: tf.keras.activations.softplus

#   - name: piy  # oil consumption this period
#     activation: tf.keras.activations.softplus
#     bounds:
#       lower: 0.00001
#       penalty_lower: 0.
#       upper: 0.1
#       penalty_upper: 0.

#   - name: xiy  # oil consumption this period
#     activation: tf.keras.activations.softplus
#     bounds:
#       lower: 0.0001
#       penalty_lower: 0.
#       upper: 0.1
#       penalty_upper: 0.
    
  - name: lambdKy  # capital budget
    activation: tf.keras.activations.linear
    
  - name: lambdpiy  # pi kkt
    activation: tf.keras.activations.softplus
    
  - name: lambdxiy  # xi kkt
    activation: tf.keras.activations.softplus
    



definitions:
  # ------------------------------------------------------------------------- #
  # Real and computational time
  # ------------------------------------------------------------------------- #
  - name: tau2t  # Scale back from tau to t
  - name: tau2tauplus  # Update tau to tau+1

  # ------------------------------------------------------------------------- #
  # Exogenous parameters
  # ------------------------------------------------------------------------- #
  - name: tfp  # TFP
  - name: tfp_tilde
  - name: gr_tfp  # Growth rate of TFP
  - name: lab  # Labor
  - name: gr_lab  # Annual growth rate of labor
  - name: betat  # Growth adjusted discout factor
  - name: adt #dirty energy tfp
  - name: acl # clean energy tfp
  - name: adt_tilde #dirty energy tfp
  - name: acl_tilde # clean energy tfp


  # ------------------------------------------------------------------------- #
  # Economic variables
  # ------------------------------------------------------------------------- #

  - name: lambd  # Lagrange multiplier wrt. the budget constraint
  - name: ygross  # Gross production
  - name: energy
  - name: energy_dt
  - name: energy_cl
#   - name: energy_dt_exo
#   - name: energy_cl_exo
  - name: kmn_exo
  - name: kdt_exo
  - name: kcl_exo
#   - name: lmn_exo
#   - name: ldt_exo
#   - name: lcl_exo
  - name: piy
  - name: xiy
  - name: lambdpi
  - name: lambdxi

  # ------------------------------------------------------------------------- #
  # First-derivatives of the value function
  # ------------------------------------------------------------------------- #
  - name: dvdk  # wrt. k
  - name: dvdpi  # wrt. pi
  - name: dvdxi  # wrt. xi

  # ------------------------------------------------------------------------- #
  # State variables in period t+1
  # ------------------------------------------------------------------------- #
  - name: kplus  # Capital stock tomorrow
 
