N_sim_batch: 512
# Cai and Lontzek (2019) assumed a model time horizon of 600 periods.
N_episode_length: 200
N_epochs_per_episode: 1
N_minibatch_size: 128
# N_minibatch_size: 1024
# N_minibatch_size: 2048
N_episodes: 10000
keras_precision: float32
