N_sim_batch: 100
# Cai and Lontzek (2019) assumed a model time horizon of 600 periods.
N_episode_length: 200
N_epochs_per_episode: 1
N_minibatch_size: 64
N_episodes: 10000
keras_precision: float32
# expectation_type: pseudo_random
# expectation_pseudo_draws: 5
